<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ExerciseTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // 2D упражнения (без настроек 3D)
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '2d',
                'name' => 'Тренировка слежения за объектом',
                'description' => 'Базовое упражнение для развития навыков слежения за движущимся объектом в 2D пространстве',
                'difficulty' => 'easy',
                'duration_seconds' => 60,
                'instructions' => 'Следите за движущимся объектом на экране, стараясь удерживать взгляд в центре цели.',
                'ball_count' => null,
                'ball_size' => null,
                'target_accuracy_percent' => null,
                'vertical_area' => null,
                'horizontal_area' => null,
                'distance_area' => null,
                'speed' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '2d',
                'name' => 'Тренировка конвергенции',
                'description' => 'Упражнение для улучшения способности глаз сходиться к близкому объекту',
                'difficulty' => 'medium',
                'duration_seconds' => 90,
                'instructions' => 'Следите за объектом, который движется к вам и от вас, фокусируя взгляд на нем.',
                'ball_count' => null,
                'ball_size' => null,
                'target_accuracy_percent' => null,
                'vertical_area' => null,
                'horizontal_area' => null,
                'distance_area' => null,
                'speed' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '2d',
                'name' => 'Тренировка дивергенции',
                'description' => 'Упражнение для развития способности глаз расходиться при взгляде на удаленные объекты',
                'difficulty' => 'medium',
                'duration_seconds' => 90,
                'instructions' => 'Следите за объектом, который удаляется от вас, расслабляя мышцы глаз.',
                'ball_count' => null,
                'ball_size' => null,
                'target_accuracy_percent' => null,
                'vertical_area' => null,
                'horizontal_area' => null,
                'distance_area' => null,
                'speed' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '2d',
                'name' => 'Тренировка саккад',
                'description' => 'Быстрые движения глаз между различными точками фиксации',
                'difficulty' => 'hard',
                'duration_seconds' => 120,
                'instructions' => 'Быстро переводите взгляд между появляющимися точками на экране.',
                'ball_count' => null,
                'ball_size' => null,
                'target_accuracy_percent' => null,
                'vertical_area' => null,
                'horizontal_area' => null,
                'distance_area' => null,
                'speed' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '2d',
                'name' => 'Тренировка фиксации взгляда',
                'description' => 'Упражнение для улучшения способности удерживать взгляд на неподвижном объекте',
                'difficulty' => 'easy',
                'duration_seconds' => 60,
                'instructions' => 'Удерживайте взгляд на центральной точке, не отвлекаясь на периферические объекты.',
                'ball_count' => null,
                'ball_size' => null,
                'target_accuracy_percent' => null,
                'vertical_area' => null,
                'horizontal_area' => null,
                'distance_area' => null,
                'speed' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 3D упражнения (с настройками)
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D ловля шариков - начальный уровень',
                'description' => 'Базовое упражнение для развития пространственного зрения в 3D',
                'difficulty' => 'easy',
                'duration_seconds' => 60,
                'instructions' => 'Ловите шарики, появляющиеся в трехмерном пространстве. Начните с медленной скорости.',
                'ball_count' => 10,
                'ball_size' => 3,
                'target_accuracy_percent' => 60,
                'vertical_area' => 'full',
                'horizontal_area' => 'full',
                'distance_area' => 'full',
                'speed' => 'slow',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D ловля шариков - средний уровень',
                'description' => 'Упражнение средней сложности для улучшения координации в 3D пространстве',
                'difficulty' => 'medium',
                'duration_seconds' => 90,
                'instructions' => 'Ловите шарики среднего размера с умеренной скоростью. Стремитесь к точности 70%.',
                'ball_count' => 20,
                'ball_size' => 4,
                'target_accuracy_percent' => 70,
                'vertical_area' => 'full',
                'horizontal_area' => 'full',
                'distance_area' => 'full',
                'speed' => 'medium',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D ловля шариков - продвинутый уровень',
                'description' => 'Сложное упражнение для опытных пользователей с высокой скоростью',
                'difficulty' => 'hard',
                'duration_seconds' => 120,
                'instructions' => 'Ловите маленькие шарики на высокой скорости. Требуется точность 80% и выше.',
                'ball_count' => 30,
                'ball_size' => 2,
                'target_accuracy_percent' => 80,
                'vertical_area' => 'full',
                'horizontal_area' => 'full',
                'distance_area' => 'full',
                'speed' => 'fast',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D тренировка верхней зоны',
                'description' => 'Фокусировка на верхней части пространства для развития вертикального зрения',
                'difficulty' => 'medium',
                'duration_seconds' => 90,
                'instructions' => 'Ловите шарики только в верхней части пространства. Развивает вертикальное поле зрения.',
                'ball_count' => 15,
                'ball_size' => 4,
                'target_accuracy_percent' => 65,
                'vertical_area' => 'top',
                'horizontal_area' => 'full',
                'distance_area' => 'full',
                'speed' => 'medium',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D тренировка дальнего зрения',
                'description' => 'Упражнение для развития способности фокусироваться на удаленных объектах',
                'difficulty' => 'hard',
                'duration_seconds' => 120,
                'instructions' => 'Ловите шарики в дальних зонах пространства. Требует хорошей координации и фокусировки.',
                'ball_count' => 25,
                'ball_size' => 3,
                'target_accuracy_percent' => 75,
                'vertical_area' => 'full',
                'horizontal_area' => 'full',
                'distance_area' => 'far',
                'speed' => 'medium',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'exercise_type' => '3d',
                'name' => '3D тренировка ближнего зрения',
                'description' => 'Упражнение для улучшения фокусировки на близких объектах в 3D',
                'difficulty' => 'medium',
                'duration_seconds' => 90,
                'instructions' => 'Ловите шарики в ближних зонах пространства. Развивает конвергенцию глаз.',
                'ball_count' => 18,
                'ball_size' => 5,
                'target_accuracy_percent' => 70,
                'vertical_area' => 'full',
                'horizontal_area' => 'full',
                'distance_area' => 'near',
                'speed' => 'slow',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('exercise_templates')->insert($templates);
    }
}

